bss_demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    path('', TemplateView.as_view(template_name='index.html', extra_context={'current_page': 'index'}), name='index'),
    # user
    path('user/', include('users.urls', namespace='users')),
    # post
    path('post/', include('posts.urls', namespace='posts')),
    # post
    path('review/', include('reviews.urls', namespace='reviews')),
    # resources
    path('resource/', include('resources.urls', namespace='resources')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# encoding: utf-8
"""
@desc: 帖子路由
"""

from django.urls import path

from .views import PostDetail, LikePost, AddPost, TopicDetail, StickyPost


app_name = 'posts'


urlpatterns = [
    path('detail/<int:post_id>/', PostDetail.as_view(), name='post-detail'),
    path('like/', LikePost.as_view(), name='like-post'),
    path('add/', AddPost.as_view(), name='add-post'),
    path('topic/detail/<int:topic_id>/', TopicDetail.as_view(), name='topic-detail'),
    path('sticky/', StickyPost.as_view()),
]

resources/urls.py
# encoding: utf-8
"""
@desc: 
"""

from django.urls import path

from .views import ResourceList, UploadResource, AddDownloadCount


app_name = 'resources'


urlpatterns = [
    path('list/', ResourceList.as_view(), name='resource-list'),
    path('upload/', UploadResource.as_view(), name='upload-resource'),
    path('add/count/', AddDownloadCount.as_view()),
]

users/urls.py
# encoding: utf-8
"""
@desc: 用户app路由
"""
from django.urls import path

from .views import UserRegister, UserLogin, UserLogout, UserHome, EditUserProfile, UserList

app_name = 'users'


urlpatterns = [
    path('register/', UserRegister.as_view(), name='user-register'),
    path('login/', UserLogin.as_view(), name='user-login'),
    path('logout/', UserLogout.as_view(), name='user-logout'),
    path('home/<int:user_id>/', UserHome.as_view(), name='user-home'),
    path('list/', UserList.as_view(), name='user-list'),
    path('edit/<int:user_id>/', EditUserProfile.as_view(), name='edit-profile'),
]

templates/resources/hot-item.html
<li class="list-group-item mt-1 border-0">
    <div class="resource-{{ resource.id }}">
        <div class="d-flex justify-content-between small">
            <span><strong>{{ resource.title }}</strong></span>
        </div>
        <div class="small mt-1">
            <span class="text-muted card-link">
               下载次数: <span id="download-count">{{ resource.download_count }}</span>
            </span>
            {% if request.user.is_authenticated %}
                <span class="card-link text-muted">
                    <a href="{{ resource.src.url }}" download="" data-rid="{{ resource.id }}"
                       class="badge badge-light text-success download">下载</a>
                </span>
            {% else %}
                <span class="card-link text-muted">
                    <a href="{% url 'users:user-login' %}" class="badge badge-light text-info">登录后可下载</a>
                </span>
            {% endif %}
        </div>
    </div>
</li>

templates/resources/hot-list.html
<div class="list-group list-group-flush">
    {% for resource in resources %}
        {% include 'resources/hot-item.html' with resource=resource %}
    {% endfor %}
</div>

templates/resources/item.html
<li class="list-group-item mt-1 border-0">
    <div class="resource-{{ resource.id }}">
        <div class="d-flex justify-content-between small">
            <span><strong>{{ resource.title }}</strong></span>
        </div>
        <div class="small mt-1">
            <span class="text-muted card-link">
               <a href="{{ resource.user.get_absolute_url }}">{{ resource.user }}</a>
            </span>
            <span class="text-muted card-link">
               {{ resource.created }}
            </span>
            <span class="text-muted card-link">
               下载次数: <span id="download-count">{{ resource.download_count }}</span>
            </span>
            {% if request.user.is_authenticated %}
                <span class="card-link text-muted">
                    <a href="{{ resource.src.url }}" download="" data-rid="{{ resource.id }}"
                       class="badge badge-light text-success download">下载</a>
                </span>
            {% else %}
                <span class="card-link text-muted">
                    <a href="{% url 'users:user-login' %}" class="badge badge-light text-info">登录后可下载</a>
                </span>
            {% endif %}
        </div>
    </div>
</li>

templates/resources/list.html
{% extends 'base.html' %}

{% load resource_tags %}

{% block title %}
    资源文件列表
{% endblock %}


{% block content %}
    <div class="row mb-5">
        <div class="col-md-9">
            <h6 class="border-bottom border-gray pb-2">最新资源文件</h6>
            <div class="list-group list-group-flush">
                {% for resource in object_list %}
                    {% include 'resources/item.html' with resource=resource %}
                {% endfor %}
            </div>
        </div>

        <div class="col-md-3">
            <h6 class="border-bottom border-gray pb-2">上传资源文件</h6>
            {% if request.user.is_authenticated %}
                <a href="{% url 'resources:upload-resource' %}" role="button" class="btn btn-sm btn-outline-info btn-block mt-3">
                  <i class="fa fa-upload"></i> 上传文件
                </a>
            {% else %}
                <a href="{% url 'users:user-login' %}" role="button" class="btn btn-sm btn-outline-info btn-block mt-3">
                   请先登录
                </a>
            {% endif %}
            <h6 class="border-bottom border-gray pb-2 mt-3">热门资源文件</h6>
            <div class="list-group list-group-flush">
                {% get_hot_resources 10 as hot_resources %}
                {% for resource in hot_resources %}
                    {% include 'resources/hot-item.html' with resource=resource %}
                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}


{% block js %}
    <script type="text/javascript">
        $('a.download').click(function () {
            var rid = $(this).data('rid');
            var data = {
                'rid': rid
            };
            $.ajax({
                cache: false,
                type: 'POST',
                url: '/resource/add/count/',
                data: data,
                async: true,
                success: function (response) {
                    location.reload();
                }
            });
        });
    </script>
{% endblock %}

templates/resources/upload.html
{% extends 'base.html' %}


{% block title %}
    上传文件
{% endblock %}


{% block content %}
    <div class="row mb-5">
        <div class="col-md-10 offset-md-1">
             <div class="mt-2">
                <form method="POST"
                      enctype="multipart/form-data" action="{% url 'resources:upload-resource' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" id="submit" name="submit"
                       class="btn btn-outline-success float-right mt-3" value="确认上传">
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script type="text/javascript">
      {% ifequal msg 'ko' %}
        tips('好气啊，提交失败啦', 'danger');
      {% endifequal %}
    </script>
{% endblock %}