bss_demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    path('', TemplateView.as_view(template_name='index.html', extra_context={'current_page': 'index'}), name='index'),
    # user
    path('user/', include('users.urls', namespace='users')),
    # post
    path('post/', include('posts.urls', namespace='posts')),
    # post
    path('review/', include('reviews.urls', namespace='reviews')),
    # resources
    path('resource/', include('resources.urls', namespace='resources')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# encoding: utf-8
"""
@desc: 帖子路由
"""

from django.urls import path

from .views import PostDetail, LikePost, AddPost, TopicDetail, StickyPost


app_name = 'posts'


urlpatterns = [
    path('detail/<int:post_id>/', PostDetail.as_view(), name='post-detail'),
    path('like/', LikePost.as_view(), name='like-post'),
    path('add/', AddPost.as_view(), name='add-post'),
    path('topic/detail/<int:topic_id>/', TopicDetail.as_view(), name='topic-detail'),
    path('sticky/', StickyPost.as_view()),
]

resources/urls.py
# encoding: utf-8
"""
@desc: 
"""

from django.urls import path

from .views import ResourceList, UploadResource, AddDownloadCount


app_name = 'resources'


urlpatterns = [
    path('list/', ResourceList.as_view(), name='resource-list'),
    path('upload/', UploadResource.as_view(), name='upload-resource'),
    path('add/count/', AddDownloadCount.as_view()),
]

users/urls.py
# encoding: utf-8
"""
@desc: 用户app路由
"""
from django.urls import path

from .views import UserRegister, UserLogin, UserLogout, UserHome, EditUserProfile, UserList

app_name = 'users'


urlpatterns = [
    path('register/', UserRegister.as_view(), name='user-register'),
    path('login/', UserLogin.as_view(), name='user-login'),
    path('logout/', UserLogout.as_view(), name='user-logout'),
    path('home/<int:user_id>/', UserHome.as_view(), name='user-home'),
    path('list/', UserList.as_view(), name='user-list'),
    path('edit/<int:user_id>/', EditUserProfile.as_view(), name='edit-profile'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
{% load post_tags %}
<html lang="zh-cn">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}{% endblock %}</title>
		<!-- Bootstrap CSS -->
    	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link href="{% static 'css/font-awesome.min.css' %}" rel='stylesheet'>
        <link href="{% static 'css/animate.min.css' %}" rel='stylesheet'>
    	<link rel="stylesheet" href="{% static 'css/app.css' %}" />

        {% block css %}

        {% endblock %}
	</head>
	<body class="">
		<nav class="navbar navbar-expand-xl navbar-light bg-white fixed-top border border-left-0 border-right-0 border-top-0 border-gery">

			<div class="container">
                <a class="navbar-brand" href="{% url 'index' %}"> <strong class="text-red">还是论坛啊</strong> </a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

			  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'index' %}">
                                <span class="{% ifequal 'index' current_page %} text-red {% endifequal %}">
                                     全部
                                </span>
                            </a>
                        </li>

                        {% get_topic_list as topics %}
                        {% for topic in topics %}
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{{ topic.get_absolute_url }}">
                                    <span class="{% ifequal topic.id topic_id %} text-red {% endifequal %}">
                                         {{ topic }}
                                    </span>
                                </a>
                            </li>
                        {% endfor %}

                    </ul>

                    <form class="form-inline my-2 my-lg-0">
                        <ul class="navbar-nav mr-auto">
                             {% if request.user.is_authenticated %}
                              <li class="nav-item">
                                <a class="nav-link {% ifequal 'notice' current_page %}text-red{% endifequal %}" href="#">
                                  <i class="fa fa-star-o" aria-hidden="true"></i> 关注
                                  {% if unread_count %}
                                      <span class="badge badge-pill badge-danger">{{ unread_count }}</span>
                                  {% endif %}
                                </a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link {% ifequal 'notice' current_page %}text-red{% endifequal %}" href="#">
                                  <i class="fa fa-bell-o" aria-hidden="true"></i> 信息
                                  {% if unread_count %}
                                      <span class="badge badge-pill badge-danger">{{ unread_count }}</span>
                                  {% endif %}
                              </a>
                            </li>
                              <li class="nav-item dropdown mr-3">
                                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img class="user-avatar-nav rounded" src="{{ request.user.avatar.url }}" alt="avatar" />
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a  class="dropdown-item" href="{{ request.user.get_absolute_url }}"><i class="fa fa-user-o" aria-hidden="true"></i> 个人主页</a>
                                    <a href="javascript:void(0)" class="dropdown-item logout"><i class="fa fa-sign-out" aria-hidden="true"></i> 退出登录</a>
                                </div>
                              </li>

                             <a href="{% url 'posts:add-post' %}"
                                class="btn btn-outline-danger pt-2">
                                <i class="fa fa-pencil" aria-hidden="true"></i> 发帖子
                             </a>
                          {% else %}
                             <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:user-register' %}">
                                    <span class="{% ifequal 'register' current_page %} text-red {% endifequal %}">
                                        注册
                                    </span>
                                </a>
                             </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:user-login' %}">登录</a>
                            </li>
                          {% endif %}
                       </ul>
                    </form>

			    </div>
			</div>
		</nav>

		<div class="main container" style="margin-top:74px">
            {% block content %}

            {% endblock %}
		</div>


		<!-- Optional JavaScript -->
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap-notify.min.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
             $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
             });
             {% if request.user.is_authenticated %}
                $('a.logout').click(function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '/user/logout/',
                        async: true,
                        success: function (response) {
                            if (response.msg === 'ok'){
                                tips('成功退出登录，页面即将刷新~', 'success');
                                setTimeout(function () {
                                    window.location.href = '/';
                                }, 1500);
                                return true;
                            } else {
                                tips('诶呀~，操作失败，请再试一次吧。', 'danger');
                                return false;
                            }
                        }
                    });
                });
            {% endif %}
        </script>
        <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
        {% block js %}

        {% endblock %}
	</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load post_tags %}
{% load user_tags %}
{% load resource_tags %}


{% block title %}
    首页
{% endblock %}


{% block content %}

    <div class="row">
        <div class="col-md-9">
            {% get_all_posts as posts %}
            {% include 'posts/list.html' with posts=posts %}
            {% include 'posts/list.html' with posts=posts %}

        </div>
        <div class="col-md-3">
            <h6 class="border-bottom border-gray pb-2">最新加入</h6>
            {% get_recent_users as online_users %}
            {% include 'users/list.html' with users=online_users %}
            <small class="d-block text-right mt-2">
              <a href="{% url 'users:user-list' %}">全部用户</a>
            </small>

            <h6 class="border-bottom border-gray pb-2 mt-3">热门文件</h6>
            {% get_hot_resources as resources %}
            {% include 'resources/hot-list.html' with resources=resources %}

            <small class="d-block text-right mt-2">
              <a href="{% url 'resources:resource-list' %}">全部文件</a>
            </small>

            <h6 class="border-bottom border-gray pb-2 mt-3">热门帖子</h6>
            {% get_hot_posts as hot_posts %}
            {% include 'posts/hot-list.html' with posts=hot_posts %}


        </div>
    </div>

{% endblock %}