bss_demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    path('', TemplateView.as_view(template_name='index.html', extra_context={'current_page': 'index'}), name='index'),
    # user
    path('user/', include('users.urls', namespace='users')),
    # post
    path('post/', include('posts.urls', namespace='posts')),
    # post
    path('review/', include('reviews.urls', namespace='reviews')),
    # resources
    path('resource/', include('resources.urls', namespace='resources')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# encoding: utf-8
"""
@desc: 帖子路由
"""

from django.urls import path

from .views import PostDetail, LikePost, AddPost, TopicDetail, StickyPost


app_name = 'posts'


urlpatterns = [
    path('detail/<int:post_id>/', PostDetail.as_view(), name='post-detail'),
    path('like/', LikePost.as_view(), name='like-post'),
    path('add/', AddPost.as_view(), name='add-post'),
    path('topic/detail/<int:topic_id>/', TopicDetail.as_view(), name='topic-detail'),
    path('sticky/', StickyPost.as_view()),
]

users/urls.py
# encoding: utf-8
"""
@desc: 用户app路由
"""
from django.urls import path

from .views import UserRegister, UserLogin, UserLogout, UserHome, EditUserProfile, UserList

app_name = 'users'


urlpatterns = [
    path('register/', UserRegister.as_view(), name='user-register'),
    path('login/', UserLogin.as_view(), name='user-login'),
    path('logout/', UserLogout.as_view(), name='user-logout'),
    path('home/<int:user_id>/', UserHome.as_view(), name='user-home'),
    path('list/', UserList.as_view(), name='user-list'),
    path('edit/<int:user_id>/', EditUserProfile.as_view(), name='edit-profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class UserProfile(AbstractUser):
    """
    用户表
    """
    nickname = models.CharField(max_length=32,
                                blank=True, null=True,
                                verbose_name='昵称')
    signature = models.CharField(max_length=128,
                                 blank=True, null=True,
                                 verbose_name='个性签名',
                                 default='这家伙很懒，什么都没有留下！')
    avatar = models.ImageField(upload_to='image/user/avatar', blank=True,
                               default='image/default_avatar.png', verbose_name='头像')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        """
        获取用户绝对路径
        :return:
        """
        return reverse('users:user-home', args=[self.pk])

    def __str__(self):
        if self.nickname:
            return self.nickname
        else:
            return self.username

users/forms.py
# encoding: utf-8
"""
@desc: 
"""
from django import forms

from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    """
    修改个人信息
    """
    class Meta:
        model = UserProfile
        fields = ('avatar', 'nickname', 'signature')
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'form-control border-0 pl-0'}),
            'nickname': forms.TextInput(attrs={'class': 'form-control bg-light'}),
            'signature': forms.TextInput(attrs={'class': 'form-control bg-light'}),
        }

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.hashers import make_password
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import View

from users.models import UserProfile
from users.forms import UserProfileForm


class UserRegister(View):
    """
    用户注册视图
    """
    def get(self, request):
        current_page = 'register'
        return render(request, 'users/register.html', {
            'current_page': current_page,
        })

    def post(self, request):
        # 判断是否是以ajax提交的
        if request.is_ajax():
            email = request.POST.get('email', None)
            password1 = request.POST.get('password1', None)
            password2 = request.POST.get('password2', None)
            # 确保前端提交的数据不为空
            if email and password1 and password2:
                # 切割邮箱，取@符号前面作为用户名
                username = email.split('@')[0]
                # 检查该邮箱是否被注册过
                if UserProfile.objects.filter(username=username).exists():
                    return JsonResponse({'msg': 'exists'})
                if not password1 == password2:
                    return JsonResponse({'msg': 'mismatch'})
                # 创建新的用户
                new_user = UserProfile(username=username, email=email)
                new_user.password = make_password(password2)
                new_user.save()
                return JsonResponse({'msg': 'ok'})
        return JsonResponse({'msg': 'ko'})


class CustomBackend(ModelBackend):
    """
    增加邮箱登录
    继承ModelBackend类，覆盖authenticate方法, 增加邮箱认证
    """
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            # 使用get是因为不希望用户存在两个, Q：使用并集查询
            user = UserProfile.objects.get(Q(username=username)|Q(email=username))
            # 判断密码是否匹配时，django的后台中密码加密：所以不能password==password
            # UserProfile继承的AbstractUser中有check_password(self, raw_password)方法
            if user.check_password(password):
                return user
        except BaseException as e:
            print(e)
            return None


class UserLogin(View):
    """
    用户登录视图
    """
    def get(self, request):
        return render(request, 'users/login.html')

    def post(self, request):
        if request.is_ajax():
            username = request.POST.get('username', None)
            password = request.POST.get('password', None)
            if username and password:
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return JsonResponse({'msg': 'ok'})
        return JsonResponse({'msg': 'ko'})


class UserLogout(View):
    """
    用户退出登录
    """
    def get(self, request):
        logout(request)
        return JsonResponse({'msg': 'ok'})


class UserHome(View):
    """
    用户个人主页
    """
    def get(self, request, user_id):
        user = get_object_or_404(UserProfile, id=int(user_id))
        posts = user.user_posts.all()
        reviews = user.user_reviews.all()
        replies = user.user_replies.all()
        resources = user.user_resources.all()
        return render(request, 'users/home.html', {
            'user': user,
            'posts': posts,
            'reviews': reviews,
            'replies': replies,
            'resources': resources,
        })


class UserList(View):
    """
    用户列表
    """
    def get(self, request):
        users = UserProfile.objects.all()
        return render(request, 'users/all.html', {'users': users})


class EditUserProfile(LoginRequiredMixin, View):
    """
    编辑用户资料
    """
    def get(self, request, user_id):
        user = self.get_user(request, user_id)
        form = UserProfileForm(instance=user)
        return render(request, 'users/profile.html', {
            'user': user,
            'form': form,
        })

    def post(self, request, user_id):
        user = self.get_user(request, user_id)
        form = UserProfileForm(instance=user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(user.get_absolute_url())
        return render(request, 'users/profile.html', {
            'user': user,
            'form': form,
            'msg': 'ko'
        })

    @staticmethod
    def get_user(request, user_id):
        user = get_object_or_404(UserProfile, id=int(user_id))
        check_is_request_owner(request, user)
        return user


def check_is_request_owner(request, owner):
    """
    检查是当前请求者是为所有者
    :param request:
    :param owner:
    :return: 引发Http404
    """
    if request.user != owner:
        raise Http404

templates/users/all.html
{% extends 'base.html' %}


{% block title %}
    全部用户
{% endblock %}


{% block content %}
    <h6 class="border-bottom border-gray pb-2">全部用户({{ users.count }})</h6>
    {% include 'users/list.html' with users=users %}
{% endblock %}

templates/users/home.html
{% extends 'base.html' %}

{% block title %}
    个人主页
{% endblock %}

{% block content %}
    <div class="row mb-5">
        <div class="col-md-9">
            <h6 class="border-bottom border-gray pb-2">帖子({{ posts.count }})</h6>
            <div class="user-post-list">
                {% include 'posts/list-home.html' with posts=posts %}
            </div>

            <h6 class="border-bottom border-gray pb-2 mt-4">评论({{ reviews.count }})</h6>
            <div class="user-post-list">
                {% include 'reviews/review-list-home.html' with reviews=reviews %}
            </div>


        </div>
        <div class="col-md-3">
            <h6 class="border-bottom border-gray pb-2">个人主页</h6>
            <div class="user-info text-center">
                <div class="mt-3">
                    <img class="user-avatar-post rounded" src="{{ user.avatar.url }}" alt="">
                </div>

                <div class="mt-2">
                    <span>{{ user }}</span>
                </div>
                <div class="mt-2">
                    <span>{{ user.date_joined|timesince }}前加入</span>
                </div>
                <div class="mt-1">
                    <span>{{ user.signature }}</span>
                </div>
            </div>

            {% ifequal user request.user %}
                <div class="mt-3">
                    <a target="_blank" href="{% url 'users:edit-profile' user.id %}" class="btn btn-sm btn-outline-success btn-block">
                        编辑资料
                    </a>
                </div>
            {% endifequal %}

            <h6 class="border-bottom border-gray pb-2 mt-3">上传的资源文件</h6>
            <div class="list-group list-group-flush">
                {% for resource in resources %}
                    {% include 'resources/hot-item.html' with resource=resource %}
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

templates/users/item.html
<li href="#" class="list-group-item border-0">
    <div class="media text-muted m-auto">
        <img src="{{ user.avatar.url }}" alt="" class="user-avatar mr-2 mt-1 rounded">
        <div class="media-body small lh-125 ">
            <div class="d-flex justify-content-between align-items-center w-100">
                <a href="{{ user.get_absolute_url }}">
                    <strong>{{ user }}</strong>
                </a>
                {% if request.user.is_authenticated %}
                    <a href="#" class="badge badge-light text-success">
                        <i class="fa fa-plus" aria-hidden="true"></i> 关注
                    </a>
                {% endif %}

            </div>
            <span class="text-truncate">{{ user.date_joined|timesince }}前加入</span>
        </div>
    </div>
</li>

templates/users/list.html
<div class="list-group list-group-flush">
    {% for user in users %}
        {% include 'users/item.html' with users=users %}
    {% endfor %}
</div>

templates/users/login.html
{% extends 'base.html' %}


{% block title %}
    注册
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-4 offset-md-4 p-5">
            <h5 class="mb-5 text-red">用户登录</h5>
            <label for="email">用户名/邮箱</label>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" >
                    <i class="fa fa fa-user" aria-hidden="true"></i>
                </span>
              </div>
              <input type="text" id="username" class="form-control" placeholder="用户名/邮箱">
            </div>

            <label for="password1">登录密码</label>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                </span>
              </div>
              <input type="password" id="password" class="form-control" placeholder="密码" >
            </div>


            <button type="button" id="login" class="btn btn-outline-success btn-sm btn-block mt-5">
                确认登录
            </button>
        </div>

    </div>
{% endblock %}


{% block js %}
    <script type="text/javascript">
        $('button#login').click(function () {

            var username = $.trim($('input#username').val());
            var password = $.trim($('input#password').val());


            if (username === '' || password === ''){
                tips('邮箱、密码、都不能为空', 'danger');
                return false;
            }

            var data = {
                'username': username,
                'password': password
            };

            $.ajax({
                cache: false,
                type: 'POST',
                url: '/user/login/',
                data: data,
                async: true,
                success: function (response) {
                    if(response.msg === 'ok'){
                        tips('登录成功，页面即将跳转~', 'success');
                        setTimeout(function () {
                            window.location.href = '/';
                        }, 1500);
                        return true;
                    }

                    if (response.msg === 'ko'){
                        tips('登录失败，请重新检查邮箱和密码，再试一次吧。', 'danger');
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                        return false;
                    }

                }
            });
        });
    </script>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
    编辑资料
{% endblock %}


{% block content %}
    <div class="row mb-5">
        <div class="col-md-10 offset-md-1">
            <h6 class="border-bottom border-gray pb-2">
                <a class="card-link" href="{{ user.get_absolute_url }}">个人主页</a>
                <span> / 编辑资料</span>
            </h6>
            <div class="mt-2">
                <p>当前头像:</p>
                <img class="user-avatar-post rounded mb-4" src="{{ user.avatar.url }}" alt="">

                <form method="POST"
                      enctype="multipart/form-data" action="{% url 'users:edit-profile' user.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" id="submit" name="submit"
                       class="btn btn-outline-success float-right mt-3" value="确认发布">
                </form>

            </div>

        </div>

    </div>
{% endblock %}


{% block js %}
    <script type="text/javascript">
      {% ifequal msg 'ko' %}
        tips('好气啊，提交失败啦', 'danger');
      {% endifequal %}
    </script>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}


{% block title %}
    注册
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-4 offset-md-4 p-5">
            <h5 class="mb-5 text-red">欢迎注册新用户</h5>
            <label for="email">邮箱注册</label>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" >
                    <i class="fa fa fa-envelope" aria-hidden="true"></i>
                </span>
              </div>
              <input type="email" id="email" class="form-control" placeholder="邮箱">
            </div>

            <label for="password1">登录密码</label>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                </span>
              </div>
              <input type="password" id="password1" class="form-control" placeholder="密码" >
            </div>

            <label for="password2">确认密码</label>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fa fa-lock"  aria-hidden="true"></i>
                </span>
              </div>
              <input type="password" id="password2" class="form-control" placeholder="密码" >
            </div>

            <button type="button" id="register" class="btn btn-outline-success btn-sm btn-block mt-5">
                确认注册并前往登录
            </button>
        </div>

    </div>
{% endblock %}


{% block js %}
    <script type="text/javascript">
        $('button#register').click(function () {

            var email = $.trim($('input#email').val());
            var password1 = $.trim($('input#password1').val());
            var password2 = $.trim($('input#password2').val());

            if (email === '' || password1 === '' || password2 === ''){
                tips('邮箱、密码、确认密码都不能为空', 'danger');
                return false;
            }

            var isEmail = /^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/;
            if (!(isEmail.test(email))){
                tips('邮箱格式不正确~', 'danger');
                return false;
            }


            var data = {
                'email': email,
                'password1': password1,
                'password2': password2
            };

            $.ajax({
                cache: false,
                type: 'POST',
                url: '/user/register/',
                data: data,
                async: true,
                success: function (response) {
                    if(response.msg === 'ok'){
                        tips('注册成功，页面即将跳转~', 'success');
                        setTimeout(function () {
                            window.location.href = '/user/login/';
                        }, 1500);
                        return true;
                    }

                    if (response.msg === 'ko'){
                        tips('注册失败，请重新检查邮箱和密码，稍后再试一次吧。', 'danger');
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                        return false;
                    }

                    if (response.msg === 'exists'){
                        tips('邮箱已经被注册。', 'danger');
                        return false;
                    }

                    if (response.msg === 'mismatch'){
                        tips('两次密码不一致。', 'danger');
                        return false;
                    }
                }
            });
        });
    </script>
{% endblock %}